# Generated by Django 5.2.12 on 2026-05-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_limit', models.FloatField(default=100.0)),
                ('z_limit', models.FloatField(default=200.0)),
                ('baud_rate', models.IntegerField(default=115200)),
                ('com_port', models.CharField(default='COM3', max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=300)),
                ('api_model', models.CharField(default='gpt-4o', max_length=50)),
            ],
            options={
                'verbose_name': 'Machine Configuration',
            },
        ),
        migrations.CreateModel(
            name='MachineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('connection', 'Connection'), ('disconnection', 'Disconnection'), ('job_start', 'Job Start'), ('job_complete', 'Job Complete'), ('job_error', 'Job Error'), ('emergency_stop', 'Emergency Stop'), ('validation_error', 'Validation Error')], max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
