# Generated by Django 5.2.12 on 2026-05-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineconfig',
            name='api_model',
            field=models.CharField(default='gpt-5', max_length=50),
        ),
    ]
